#!/bin/bash

MYSCONS=$1
export SCONS_LIB_DIR=$MYSCONS/engine
if [ -f $MYSCONS/script/scons.py ]
then
  python $MYSCONS/script/scons.py $2 $3 $4 $5 $6 $7 $8 $9
else
  if [ -f $MYSCONS/script/scons ]
  then
    python $MYSCONS/script/scons $2 $3 $4 $5 $6 $7 $8 $9
  else
    echo "No SCons script found in '$MYSCONS/script'!"
  fi
fi

